version: "3.7"

services:
  app:
    image: shaddar/node:nextjs-blog-v0.1
    command: bash -c "npm start"
    ports:
      - 8332:3000
    volumes:
      - type: bind
        source: ~/Documents/workspace/personal/nextjs-blog/run
        target: /var/app/data/

