version: "3.7"

services:
  app:
    image: shaddar/node:nextjs-blog-v0.1
    command: bash -c "npm start"
    ports:
      - 8332:3000
    volumes:
      - type: bind
        source: /home/shaddar/Documents/workspace/personal/nextjs-blog/run/data/
        target: /var/app/data/


# volumes:
#   blog_data:
#     driver: local
#     o: bind
#     device:

